/******************************************************************************
* File Name:   main.c
*
* Description: This is the source code for the XMC MCU: UART DMA Example
*              for ModusToolbox. This example demonstrates how to stream data
*              using DMA via a Universal Serial Interface Channel (USIC)
*              based UART to external terminal.
*
* Related Document: See README.md
*
******************************************************************************
*
* Copyright (c) 2015-2020, Infineon Technologies AG
* All rights reserved.                        
*                                             
* Boost Software License - Version 1.0 - August 17th, 2003
* 
* Permission is hereby granted, free of charge, to any person or organization
* obtaining a copy of the software and accompanying documentation covered by
* this license (the "Software") to use, reproduce, display, distribute,
* execute, and transmit the Software, and to prepare derivative works of the
* Software, and to permit third-parties to whom the Software is furnished to
* do so, all subject to the following:
* 
* The copyright notices in the Software and this entire statement, including
* the above license grant, this restriction and the following disclaimer,
* must be included in all copies of the Software, in whole or in part, and
* all derivative works of the Software, unless such copies or derivative
* works are solely in the form of machine-executable object code generated by
* a source language processor.
* 
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
* SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
* FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
* DEALINGS IN THE SOFTWARE.
*                                                                              
*****************************************************************************/

#include "cybsp.h"
#include "cy_utils.h"

#include "xmc_dma.h"

/*******************************************************************************
* Macros
*******************************************************************************/
/* Size of source buffer(s) for the DMA to read from */
#define BUFFER_LENGTH                           256

/* Preemptive priority value (starting from 0) of NVIC CPU Subsystem */
#define DEBUG_GPDMA_RECEIVE_EVENT_PRIORITY      63

/* Subpriority value (starting from 0) of NVIC CPU Subsystem */
#define DEBUG_GPDMA_RECEIVE_EVENT_SUB_PRIORITY  0

/* DMA Channel 2 */
#define GPDMA_CHANNEL_2                         2

/*******************************************************************************
* Global Variables
*******************************************************************************/
/* Source buffers for DMA */
uint8_t buffer1[BUFFER_LENGTH];
uint8_t buffer2[BUFFER_LENGTH];

/* Flag variable to register when transfer is finished */
volatile bool transfer_done = false;

/* Configuration of DMA */
XMC_DMA_CH_CONFIG_t dma_ch_config =
{
  .dst_addr = (uint32_t)&(CYBSP_DEBUG_UART_HW->TBUF[0]),              /* Destination address */
  .src_transfer_width = XMC_DMA_CH_TRANSFER_WIDTH_8,                  /* Source transfer width (:: XMC_DMA_CH_TRANSFER_WIDTH_t) */
  .dst_transfer_width = XMC_DMA_CH_TRANSFER_WIDTH_8,                  /* Destination transfer width (:: XMC_DMA_CH_TRANSFER_WIDTH_t) */
  .src_address_count_mode = XMC_DMA_CH_ADDRESS_COUNT_MODE_INCREMENT,  /* Source address count mode (:: XMC_DMA_CH_ADDRESS_COUNT_MODE_t) */
  .dst_address_count_mode = XMC_DMA_CH_ADDRESS_COUNT_MODE_NO_CHANGE,  /* Destination address count mode (:: XMC_DMA_CH_ADDRESS_COUNT_MODE_t) */
  .src_burst_length = XMC_DMA_CH_BURST_LENGTH_8,                      /* Source burst length (:: XMC_DMA_CH_BURST_LENGTH_t) */
  .dst_burst_length = XMC_DMA_CH_BURST_LENGTH_1,                      /* Destination burst length (:: XMC_DMA_CH_BURST_LENGTH_t) */
  .transfer_flow = XMC_DMA_CH_TRANSFER_FLOW_M2P_DMA,                  /* DMA transfer flow (:: XMC_DMA_CH_TRANSFER_FLOW_t) */
  .transfer_type = XMC_DMA_CH_TRANSFER_TYPE_SINGLE_BLOCK,             /* DMA transfer type (:: XMC_DMA_CH_TRANSFER_TYPE_t) */
  .dst_handshaking = XMC_DMA_CH_DST_HANDSHAKING_HARDWARE,             /* DMA destination handshaking interface (:: XMC_DMA_CH_DST_HANDSHAKING_t) */
  .dst_peripheral_request = DMA0_PERIPHERAL_REQUEST_USIC0_SR0_0,      /* Destination peripheral request. See xmc_dma_map.h */
  .enable_interrupt = true
};

/*******************************************************************************
* Function Name: GPDMA0_0_IRQHandler
********************************************************************************
* Summary:
* Interrupt handler called when transfer has completed
*
* Parameters:
*  void
*
* Return:
*  void
*
*******************************************************************************/
void GPDMA0_0_IRQHandler(void)
{
  /* Set global variable to register event and notify main-loop */
  transfer_done = true;

  /* Clear event status */
  XMC_DMA_CH_ClearEventStatus(XMC_DMA0, GPDMA_CHANNEL_2, XMC_DMA_CH_EVENT_BLOCK_TRANSFER_COMPLETE);
}

/*******************************************************************************
* Function Name: main
********************************************************************************
* Summary:
* This is the main function. It initializes the UART interface and configures
* DMA for streaming via UART.
* Waits for the transfer to finish and finally idles inside main-loop.
*
* Parameters:
*  void
*
* Return:
*  int
*
*******************************************************************************/
int main(void)
{
    cy_rslt_t result;

    /* Initialize the device and board peripherals */
    result = cybsp_init();
    if (result != CY_RSLT_SUCCESS)
    {
        CY_ASSERT(0);
    }
    
    /* Prepare source buffers with ASCII-codes A..Z and a..z */ 
    for (uint32_t i = 0; i < BUFFER_LENGTH; ++i)
    {
        buffer1[i] = i%26 + 'A';
        buffer2[i] = i%26 + 'a'; 
    }

    /* Initialize DMA */
    XMC_DMA_Init(XMC_DMA0);
    if (XMC_DMA_CH_Init(XMC_DMA0, GPDMA_CHANNEL_2, &dma_ch_config) != XMC_DMA_CH_STATUS_OK)
    {
        CY_ASSERT(0);
    }

    /* Enable DMA event handling */
    XMC_DMA_CH_EnableEvent(XMC_DMA0, GPDMA_CHANNEL_2, XMC_DMA_CH_EVENT_BLOCK_TRANSFER_COMPLETE);
    NVIC_SetPriority(GPDMA0_0_IRQn, NVIC_EncodePriority(NVIC_GetPriorityGrouping(), DEBUG_GPDMA_RECEIVE_EVENT_PRIORITY, DEBUG_GPDMA_RECEIVE_EVENT_SUB_PRIORITY));
    NVIC_EnableIRQ(GPDMA0_0_IRQn);

    /* Initial trigger for DMA transfer */
    XMC_USIC_CH_TriggerServiceRequest(XMC_UART0_CH0, 0);

    /* Execute DMA transfer of buffer 1 */
    transfer_done = false;
    /* Set Block size of the next transfer */
    XMC_DMA_CH_SetBlockSize(XMC_DMA0, GPDMA_CHANNEL_2, BUFFER_LENGTH);
    /* Set Source address of the next transfer */
    XMC_DMA_CH_SetSourceAddress(XMC_DMA0, GPDMA_CHANNEL_2, (uint32_t)&buffer1[0]);
    /* Start transfer */
    XMC_DMA_CH_Enable(XMC_DMA0, GPDMA_CHANNEL_2);

    /* Wait for completion of DMA transfer */
    while (transfer_done == false);

    /* Execute DMA transfer of buffer 2 */
    transfer_done = false;
    /* Set Block size of the next transfer */
    XMC_DMA_CH_SetBlockSize(XMC_DMA0, GPDMA_CHANNEL_2, BUFFER_LENGTH);
    /* Set Source address of the next transfer */
    XMC_DMA_CH_SetSourceAddress(XMC_DMA0, GPDMA_CHANNEL_2, (uint32_t)&buffer2[0]);
    /* Start transfer */
    XMC_DMA_CH_Enable(XMC_DMA0, GPDMA_CHANNEL_2);

    /* Wait for completion of DMA transfer */
    while (transfer_done == false);

    while(1);
}

/* [] END OF FILE */
